# Generated by Django 4.2.1 on 2023-06-06 12:51

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='012345678', length=8, max_length=40, prefix='', primary_key=True, serialize=False),
        ),
    ]
